window.I18N = {
  "Invalid Cohort ID provided.": "Ungültige Kohorten-ID angegeben.",
  "Passphrase must be a string.": "Die Passphrase muss eine Zeichenkette sein.",
  "Invalid Job ID provided.": "Ungültige Job-ID angegeben.",
  "Alias must be a string.": "Der Alias muss eine Zeichenkette sein.",
  "Job failed.": "Job fehlgeschlagen.",
  "Invalid cohort status data.": "Ungültige Statusdaten der Kohorte.",
  "Cohort processing failed.": "Verarbeitung der Kohorte fehlgeschlagen.",
  "Invalid alias provided.": "Ungültiger Alias angegeben.",
  "Passphrase is required for cohort analysis.": "Für die Kohortenanalyse ist eine Passphrase erforderlich.",
  "Failed to initialize the virtual filesystem (CLI.fs is undefined).": "Das virtuelle Dateisystem konnte nicht initialisiert werden (CLI.fs ist nicht definiert).",
  "Failed to initialize the processing environment.": "Die Verarbeitungsumgebung konnte nicht initialisiert werden.",
  "⚠️  Pipeline Warning: The Dragen pipeline has known issues aligning reads in the MUC1 VNTR region. For best results, consider using the offline VNtyper CLI in normal mode.": "⚠️  Pipeline-Warnung: Die Dragen-Pipeline hat bekannte Probleme beim Alignment von Reads in der MUC1-VNTR-Region. Für bestmögliche Ergebnisse empfiehlt sich die Offline-Version (VNtyper CLI) im normalen Modus.",
  "⚠️  Pipeline Warning: The CLC pipeline has not been fully tested and may have issues aligning reads in the MUC1 VNTR region. Please verify results carefully or use the offline VNtyper CLI.": "⚠️  Pipeline-Warnung: Die CLC-Pipeline wurde nicht vollständig getestet und kann Probleme beim Alignment von Reads in der MUC1-VNTR-Region haben. Bitte prüfen Sie die Ergebnisse sorgfältig oder verwenden Sie die Offline-Version (VNtyper CLI).",
  "No region selected.": "Keine Region ausgewählt.",
  "Processing...": "Wird verarbeitet...",
  "Failed to mount SAM file: {name}": "SAM-Datei konnte nicht eingebunden werden: {name}",
  "Failed to create Blob from BAM file {file}.": "Blob aus BAM-Datei {file} konnte nicht erstellt werden.",
  "Failed to create Blob from BAI file {file}.": "Blob aus BAI-Datei {file} konnte nicht erstellt werden.",
  "Error: {message}": "Fehler: {message}",
  "Extract Region": "Region extrahieren",
  "Submit Job": "Job absenden",
  "Submitting...": "Wird gesendet...",
  "No files selected. Please upload BAM and BAI files.": "Keine Dateien ausgewählt. Bitte laden Sie BAM- und BAI-Dateien hoch.",
  "Extracting...": "Wird extrahiert...",
  "Processing BAM file extraction...": "BAM-Datei wird extrahiert...",
  "Submit Jobs": "Jobs absenden",
  "Your results will appear here after job submission.": "Ihre Ergebnisse erscheinen hier, nachdem Sie Jobs abgesendet haben.",
  "Download {name}": "{name} herunterladen",
  "Download subset BAM file {name}": "BAM-Teildatei {name} herunterladen",
  "Download subset BAI file {name}": "BAI-Teildatei {name} herunterladen",
  "Invalid Job ID provided": "Ungültige Job-ID angegeben",
  "Job failed": "Job fehlgeschlagen",
  "Load Job from URL": "Job über URL laden",
  "Cohort Creation": "Kohortenerstellung",
  "Cohort failed.": "Kohorte fehlgeschlagen.",
  "Cohort passphrase is required to run joint analysis.": "Für die gemeinsame Analyse ist die Kohorten-Passphrase erforderlich.",
  "Cohort Analysis": "Kohortenanalyse",
  "Initiating joint analysis...": "Gemeinsame Analyse wird gestartet...",
  "Analysis in progress...": "Analyse läuft...",
  "Cohort analysis failed.": "Kohortenanalyse fehlgeschlagen.",
  "Aioli Initialization": "Aioli-Initialisierung",
  "BAM Extraction": "BAM-Extraktion",
  "File Selection": "Dateiauswahl",
  "Invalid files: {files}": "Ungültige Dateien: {files}",
  "File Validation": "Dateivalidierung",
  "Job Submission": "Absenden des Jobs",
  "Job {id} not found": "Job {id} nicht gefunden",
  "Job Retry": "Job-Wiederholung",
  "Disclaimer": "Disclaimer",
  "GDPR explicit consent is required to donate data.": "Für die Datenspende ist eine ausdrückliche Einwilligung gemäß DSGVO erforderlich.",
  "Please select a result ZIP archive to donate.": "Bitte wählen Sie ein ZIP-Archiv mit Ergebnissen für die Spende aus.",
  "Please select a valid .zip result file.": "Bitte wählen Sie eine gültige .zip-Ergebnisdatei aus.",
  "Confirmation method is required for positive findings.": "Für positive Ergebnisse ist die Angabe der Bestätigungsmethode erforderlich.",
  "Verifying and uploading donation...": "Spende wird geprüft und hochgeladen...",
  "Server responded with {status}: {statusText}": "Server antwortete mit {status}: {statusText}",
  "Remove {name}": "{name} entfernen",
  "No files selected.": "Keine Dateien ausgewählt.",
  "Some files were invalid and not added: {files}": "Einige Dateien waren ungültig und wurden nicht hinzugefügt: {files}",
  "Processing files...": "Dateien werden verarbeitet...",
  "Please enter a valid email address (e.g., user@example.com)": "Bitte geben Sie eine gültige E-Mail-Adresse ein (z. B. user@example.com)",
  "Valid email address": "Gültige E-Mail-Adresse",
  "Cohort alias must be 3-64 characters (letters, numbers, spaces, hyphens, underscores)": "Der Kohorten-Alias muss 3-64 Zeichen lang sein (Buchstaben, Ziffern, Leerzeichen, Bindestriche, Unterstriche)",
  "Valid cohort alias": "Gültiger Kohorten-Alias",
  "Passphrase must be 8-128 characters long": "Die Passphrase muss 8-128 Zeichen lang sein",
  "Valid passphrase": "Gültige Passphrase",
  "Job ID: ": "Job-ID: ",
  "Status: ": "Status: ",
  "Loading cohort details for Cohort ID: ": "Kohortendetails werden geladen für Kohorten-ID: ",
  "Loading...": "Wird geladen...",
  "Loading job details for Job ID: ": "Jobdetails werden geladen für Job-ID: ",
  "No logs to download": "Keine Logs zum Herunterladen",
  "Clear all logs?": "Alle Logs löschen?",
  "Cohort ID must be a non-empty string": "Die Kohorten-ID muss eine nicht leere Zeichenkette sein",
  "Invalid cohort ID format: {id}": "Ungültiges Format der Kohorten-ID: {id}",
  "Job ID must be a non-empty string": "Die Job-ID muss eine nicht leere Zeichenkette sein",
  "Invalid job ID format: {id}": "Ungültiges Format der Job-ID: {id}",
  "Invalid job status: {status}": "Ungültiger Job-Status: {status}",
  "Polling duration exceeded": "Maximale Abfragedauer überschritten",
  "hg19 (UCSC chr prefix)": "hg19 (UCSC, chr-Präfix)",
  "hg38 (UCSC chr prefix)": "hg38 (UCSC, chr-Präfix)",
  "GRCh37 (ENSEMBL numeric)": "GRCh37 (ENSEMBL, numerisch)",
  "GRCh38 (ENSEMBL numeric)": "GRCh38 (ENSEMBL, numerisch)",
  "hg19 (NCBI RefSeq)": "hg19 (NCBI RefSeq)",
  "hg38 (NCBI RefSeq)": "hg38 (NCBI RefSeq)",
  "Request timeout after {timeout}ms": "Zeitüberschreitung der Anfrage nach {timeout} ms",
  "Request failed with status {status}": "Anfrage fehlgeschlagen mit Status {status}",
  "Next": "Weiter",
  "Back": "Zurück",
  "Done": "Fertig",
  "Shareable Link: ": "Teilbarer Link: ",
  "Shareable link for {type} ID {id}": "Teilbarer Link für {type}-ID {id}",
  "Copy link": "Link kopieren",
  "Failed to copy the link. Please try manually.": "Der Link konnte nicht kopiert werden. Bitte kopieren Sie ihn manuell.",
  "Download vntyper results": "VNtyper-Ergebnisse herunterladen",
  "Download results for Job ID {jobId}": "Ergebnisse für Job-ID {jobId} herunterladen",
  "Copy Link": "Link kopieren",
  "Copy shareable link for Job ID {jobId}": "Teilbaren Link für Job-ID {jobId} kopieren",
  "Shareable link copied to clipboard!": "Teilbarer Link in die Zwischenablage kopiert!",
  "Detected reference assembly:": "Erkanntes Referenzgenom:",
  "Coordinates configured automatically. Please confirm or select manually.": "Koordinaten automatisch konfiguriert. Bitte bestätigen oder manuell auswählen.",
  "Hide options": "Optionen ausblenden",
  "Show options": "Optionen anzeigen",
  "Next poll in: {seconds} seconds": "Nächste Abfrage in: {seconds} Sekunden",
  "Failed to fetch usage statistics: {status}": "Nutzungsstatistiken konnten nicht abgerufen werden: {status}",
  "Active Jobs": "Aktive Jobs",
  "Unique Users": "Eindeutige Nutzer",
  "Active Window Statuses": "Status im aktiven Zeitfenster",
  "No active jobs in window": "Keine aktiven Jobs im Zeitfenster",
  "Cumulative Usage Tracking": "Kumulative Nutzungserfassung",
  "All-time jobs: {jobs} | All-time users: {users}": "Jobs gesamt: {jobs} | Nutzer gesamt: {users}",
  "Cumulative tracking recorded since {date}": "Kumulative Erfassung seit {date}",
  "N/A": "k. A.",
  "Running Joint Analysis...": "Gemeinsame Analyse läuft...",
  "Retry Joint Analysis": "Gemeinsame Analyse wiederholen",
  "Analysis Completed": "Analyse abgeschlossen",
  "Analysis Complete": "Analyse abgeschlossen",
  "Download Cohort Results (.zip)": "Kohortenergebnisse herunterladen (.zip)",
  "Cohort: {name}": "Kohorte: {name}",
  "ID: ": "ID: ",
  "Jobs: ": "Jobs: ",
  "Joint Cohort Analysis": "Gemeinsame Kohortenanalyse",
  "All cohort samples have completed processing. Run joint analysis to aggregate screening calls, compute cohort allele frequencies, and generate summary visualizations.": "Alle Proben der Kohorte wurden verarbeitet. Starten Sie die gemeinsame Analyse, um Screening-Calls zusammenzuführen, Allelfrequenzen der Kohorte zu berechnen und zusammenfassende Visualisierungen zu erstellen.",
  "Run Joint Analysis": "Gemeinsame Analyse starten",
  "Pending": "Ausstehend",
  "Processing": "In Bearbeitung",
  "Completed": "Abgeschlossen",
  "Failed": "Fehlgeschlagen",
  "Validation Error: {message}": "Validierungsfehler: {message}",
  "Network Error": "Netzwerkfehler",
  "API Error ({statusCode})": "API-Fehler ({statusCode})",
  "API Error": "API-Fehler",
  "Error": "Fehler",
  "Download Results": "Ergebnisse herunterladen",
  "File: ": "Datei: ",
  "Queued": "In Warteschlange",
  "Started": "Gestartet",
  "Cancelled": "Abgebrochen"
};
