# frontend/Dockerfile

FROM nginx:1.31.6-alpine-slim

# Upgrade packages to patch OS vulnerabilities and install gettext, bash, and curl for health checks
RUN apk update && apk upgrade --no-cache && apk add --no-cache gettext bash curl

RUN rm -rf /usr/share/nginx/html/*

# Allow-list the web root.
#
# `COPY .` published every repository file that .dockerignore happened not to
# name - package manifests, Makefile, ESLint/vitest config, the test suite and
# CI workflows - and exposed every future file by default. Copy only what the
# site actually serves.
COPY index.html adtkd_diagnostics.html contact.html      impressum_en.html impressum_de.html donate.html      robots.txt sitemap.xml /usr/share/nginx/html/
COPY resources/ /usr/share/nginx/html/resources/
# Translated sites, generated by scripts/sync-i18n.mjs - one line per locale in i18n/config.json.
COPY de/ /usr/share/nginx/html/de/
COPY fr/ /usr/share/nginx/html/fr/
COPY it/ /usr/share/nginx/html/it/
COPY es/ /usr/share/nginx/html/es/
COPY nl/ /usr/share/nginx/html/nl/

EXPOSE 80

# Add HEALTHCHECK to ensure frontend is responding
HEALTHCHECK --interval=60s --timeout=5s --retries=3 CMD curl -f http://localhost || exit 1
