window.I18N = {
  "Invalid Cohort ID provided.": "ID coorte non valido.",
  "Passphrase must be a string.": "La passphrase deve essere una stringa.",
  "Invalid Job ID provided.": "ID job non valido.",
  "Alias must be a string.": "L'alias deve essere una stringa.",
  "Job failed.": "Job non riuscito.",
  "Invalid cohort status data.": "Dati di stato della coorte non validi.",
  "Cohort processing failed.": "Elaborazione della coorte non riuscita.",
  "Invalid alias provided.": "Alias non valido.",
  "Passphrase is required for cohort analysis.": "Per l'analisi di coorte è richiesta la passphrase.",
  "Failed to initialize the virtual filesystem (CLI.fs is undefined).": "Impossibile inizializzare il file system virtuale (CLI.fs non è definito).",
  "Failed to initialize the processing environment.": "Impossibile inizializzare l'ambiente di elaborazione.",
  "⚠️  Pipeline Warning: The Dragen pipeline has known issues aligning reads in the MUC1 VNTR region. For best results, consider using the offline VNtyper CLI in normal mode.": "⚠️  Avviso pipeline: la pipeline Dragen presenta problemi noti nell'allineamento delle read nella regione del VNTR di MUC1. Per risultati ottimali, si consiglia di utilizzare la CLI offline di VNtyper in modalità normale.",
  "⚠️  Pipeline Warning: The CLC pipeline has not been fully tested and may have issues aligning reads in the MUC1 VNTR region. Please verify results carefully or use the offline VNtyper CLI.": "⚠️  Avviso pipeline: la pipeline CLC non è stata completamente testata e potrebbe presentare problemi nell'allineamento delle read nella regione del VNTR di MUC1. Verificare attentamente i risultati oppure utilizzare la CLI offline di VNtyper.",
  "No region selected.": "Nessuna regione selezionata.",
  "Processing...": "Elaborazione in corso...",
  "Failed to mount SAM file: {name}": "Impossibile montare il file SAM: {name}",
  "Failed to create Blob from BAM file {file}.": "Impossibile creare il Blob dal file BAM {file}.",
  "Failed to create Blob from BAI file {file}.": "Impossibile creare il Blob dal file BAI {file}.",
  "Error: {message}": "Errore: {message}",
  "Extract Region": "Estrai regione",
  "Submit Job": "Invia job",
  "Submitting...": "Invio in corso...",
  "No files selected. Please upload BAM and BAI files.": "Nessun file selezionato. Caricare i file BAM e BAI.",
  "Extracting...": "Estrazione in corso...",
  "Processing BAM file extraction...": "Estrazione dal file BAM in corso...",
  "Submit Jobs": "Invia job",
  "Your results will appear here after job submission.": "I risultati appariranno qui dopo l'invio del job.",
  "Download {name}": "Scarica {name}",
  "Download subset BAM file {name}": "Scarica il file BAM estratto {name}",
  "Download subset BAI file {name}": "Scarica il file BAI estratto {name}",
  "Invalid Job ID provided": "ID job non valido",
  "Job failed": "Job non riuscito",
  "Load Job from URL": "Carica job da URL",
  "Cohort Creation": "Creazione della coorte",
  "Cohort failed.": "Coorte non riuscita.",
  "Cohort passphrase is required to run joint analysis.": "Per eseguire l'analisi congiunta è richiesta la passphrase della coorte.",
  "Cohort Analysis": "Analisi di coorte",
  "Initiating joint analysis...": "Avvio dell'analisi congiunta...",
  "Analysis in progress...": "Analisi in corso...",
  "Cohort analysis failed.": "Analisi di coorte non riuscita.",
  "Aioli Initialization": "Inizializzazione di Aioli",
  "BAM Extraction": "Estrazione BAM",
  "File Selection": "Selezione dei file",
  "Invalid files: {files}": "File non validi: {files}",
  "File Validation": "Validazione dei file",
  "Job Submission": "Invio del job",
  "Job {id} not found": "Job {id} non trovato",
  "Job Retry": "Nuovo tentativo job",
  "Disclaimer": "Disclaimer",
  "GDPR explicit consent is required to donate data.": "Per donare i dati è richiesto il consenso esplicito ai sensi del GDPR.",
  "Please select a result ZIP archive to donate.": "Selezionare un archivio ZIP dei risultati da donare.",
  "Please select a valid .zip result file.": "Selezionare un file di risultati .zip valido.",
  "Confirmation method is required for positive findings.": "Per i risultati positivi è richiesto il metodo di conferma.",
  "Verifying and uploading donation...": "Verifica e caricamento della donazione in corso...",
  "Server responded with {status}: {statusText}": "Il server ha risposto con {status}: {statusText}",
  "Remove {name}": "Rimuovi {name}",
  "No files selected.": "Nessun file selezionato.",
  "Some files were invalid and not added: {files}": "Alcuni file non erano validi e non sono stati aggiunti: {files}",
  "Processing files...": "Elaborazione dei file...",
  "Please enter a valid email address (e.g., user@example.com)": "Inserire un indirizzo e-mail valido (ad es. user@example.com)",
  "Valid email address": "Indirizzo e-mail valido",
  "Cohort alias must be 3-64 characters (letters, numbers, spaces, hyphens, underscores)": "L'alias della coorte deve contenere da 3 a 64 caratteri (lettere, numeri, spazi, trattini, trattini bassi)",
  "Valid cohort alias": "Alias della coorte valido",
  "Passphrase must be 8-128 characters long": "La passphrase deve contenere da 8 a 128 caratteri",
  "Valid passphrase": "Passphrase valida",
  "Job ID: ": "ID job: ",
  "Status: ": "Stato: ",
  "Loading cohort details for Cohort ID: ": "Caricamento dei dettagli della coorte per l'ID coorte: ",
  "Loading...": "Caricamento...",
  "Loading job details for Job ID: ": "Caricamento dei dettagli del job per l'ID job: ",
  "No logs to download": "Nessun log da scaricare",
  "Clear all logs?": "Cancellare tutti i log?",
  "Cohort ID must be a non-empty string": "L'ID coorte deve essere una stringa non vuota",
  "Invalid cohort ID format: {id}": "Formato dell'ID coorte non valido: {id}",
  "Job ID must be a non-empty string": "L'ID job deve essere una stringa non vuota",
  "Invalid job ID format: {id}": "Formato dell'ID job non valido: {id}",
  "Invalid job status: {status}": "Stato del job non valido: {status}",
  "Polling duration exceeded": "Durata massima del polling superata",
  "hg19 (UCSC chr prefix)": "hg19 (prefisso chr UCSC)",
  "hg38 (UCSC chr prefix)": "hg38 (prefisso chr UCSC)",
  "GRCh37 (ENSEMBL numeric)": "GRCh37 (ENSEMBL numerico)",
  "GRCh38 (ENSEMBL numeric)": "GRCh38 (ENSEMBL numerico)",
  "hg19 (NCBI RefSeq)": "hg19 (NCBI RefSeq)",
  "hg38 (NCBI RefSeq)": "hg38 (NCBI RefSeq)",
  "Request timeout after {timeout}ms": "Timeout della richiesta dopo {timeout}ms",
  "Request failed with status {status}": "Richiesta non riuscita con stato {status}",
  "Next": "Avanti",
  "Back": "Indietro",
  "Done": "Fine",
  "Shareable Link: ": "Link condivisibile: ",
  "Shareable link for {type} ID {id}": "Link condivisibile per l'ID {type} {id}",
  "Copy link": "Copia link",
  "Failed to copy the link. Please try manually.": "Impossibile copiare il link. Copiarlo manualmente.",
  "Download vntyper results": "Scarica i risultati di vntyper",
  "Download results for Job ID {jobId}": "Scarica i risultati per l'ID job {jobId}",
  "Copy Link": "Copia link",
  "Copy shareable link for Job ID {jobId}": "Copia il link condivisibile per l'ID job {jobId}",
  "Shareable link copied to clipboard!": "Link condivisibile copiato negli appunti!",
  "Detected reference assembly:": "Assembly di riferimento rilevato:",
  "Coordinates configured automatically. Please confirm or select manually.": "Coordinate configurate automaticamente. Confermare o selezionare manualmente.",
  "Hide options": "Nascondi opzioni",
  "Show options": "Mostra opzioni",
  "Next poll in: {seconds} seconds": "Prossimo aggiornamento tra: {seconds} secondi",
  "Failed to fetch usage statistics: {status}": "Impossibile recuperare le statistiche di utilizzo: {status}",
  "Active Jobs": "Job attivi",
  "Unique Users": "Utenti unici",
  "Active Window Statuses": "Stati nella finestra attiva",
  "No active jobs in window": "Nessun job attivo nella finestra",
  "Cumulative Usage Tracking": "Monitoraggio cumulativo dell'utilizzo",
  "All-time jobs: {jobs} | All-time users: {users}": "Job totali: {jobs} | Utenti totali: {users}",
  "Cumulative tracking recorded since {date}": "Monitoraggio cumulativo registrato dal {date}",
  "N/A": "N/D",
  "Running Joint Analysis...": "Analisi congiunta in corso...",
  "Retry Joint Analysis": "Riprova analisi congiunta",
  "Analysis Completed": "Analisi completata",
  "Analysis Complete": "Analisi completata",
  "Download Cohort Results (.zip)": "Scarica i risultati della coorte (.zip)",
  "Cohort: {name}": "Coorte: {name}",
  "ID: ": "ID: ",
  "Jobs: ": "Job: ",
  "Joint Cohort Analysis": "Analisi congiunta di coorte",
  "All cohort samples have completed processing. Run joint analysis to aggregate screening calls, compute cohort allele frequencies, and generate summary visualizations.": "Tutti i campioni della coorte sono stati elaborati. Eseguire l'analisi congiunta per aggregare le chiamate di screening, calcolare le frequenze alleliche della coorte e generare visualizzazioni riepilogative.",
  "Run Joint Analysis": "Esegui analisi congiunta",
  "Pending": "In attesa",
  "Processing": "In elaborazione",
  "Completed": "Completato",
  "Failed": "Non riuscito",
  "Validation Error: {message}": "Errore di validazione: {message}",
  "Network Error": "Errore di rete",
  "API Error ({statusCode})": "Errore API ({statusCode})",
  "API Error": "Errore API",
  "Error": "Errore",
  "Download Results": "Scarica risultati",
  "File: ": "File: ",
  "Queued": "In coda",
  "Started": "Avviato",
  "Cancelled": "Annullato"
};
