window.I18N = {
  "Invalid Cohort ID provided.": "El ID de cohorte indicado no es válido.",
  "Passphrase must be a string.": "La frase de contraseña debe ser una cadena de texto.",
  "Invalid Job ID provided.": "El ID de trabajo indicado no es válido.",
  "Alias must be a string.": "El alias debe ser una cadena de texto.",
  "Job failed.": "El trabajo ha fallado.",
  "Invalid cohort status data.": "Datos de estado de la cohorte no válidos.",
  "Cohort processing failed.": "El procesamiento de la cohorte ha fallado.",
  "Invalid alias provided.": "El alias indicado no es válido.",
  "Passphrase is required for cohort analysis.": "Se requiere la frase de contraseña para el análisis de cohorte.",
  "Failed to initialize the virtual filesystem (CLI.fs is undefined).": "No se pudo inicializar el sistema de archivos virtual (CLI.fs no está definido).",
  "Failed to initialize the processing environment.": "No se pudo inicializar el entorno de procesamiento.",
  "⚠️  Pipeline Warning: The Dragen pipeline has known issues aligning reads in the MUC1 VNTR region. For best results, consider using the offline VNtyper CLI in normal mode.": "⚠️  Advertencia sobre el pipeline: el pipeline Dragen presenta problemas conocidos al alinear lecturas en la región del VNTR de MUC1. Para obtener mejores resultados, considere utilizar la CLI de VNtyper sin conexión en modo normal.",
  "⚠️  Pipeline Warning: The CLC pipeline has not been fully tested and may have issues aligning reads in the MUC1 VNTR region. Please verify results carefully or use the offline VNtyper CLI.": "⚠️  Advertencia sobre el pipeline: el pipeline CLC no se ha probado por completo y puede presentar problemas al alinear lecturas en la región del VNTR de MUC1. Verifique los resultados con atención o utilice la CLI de VNtyper sin conexión.",
  "No region selected.": "No se ha seleccionado ninguna región.",
  "Processing...": "Procesando...",
  "Failed to mount SAM file: {name}": "No se pudo montar el archivo SAM: {name}",
  "Failed to create Blob from BAM file {file}.": "No se pudo crear el Blob a partir del archivo BAM {file}.",
  "Failed to create Blob from BAI file {file}.": "No se pudo crear el Blob a partir del archivo BAI {file}.",
  "Error: {message}": "Error: {message}",
  "Extract Region": "Extraer región",
  "Submit Job": "Enviar trabajo",
  "Submitting...": "Enviando...",
  "No files selected. Please upload BAM and BAI files.": "No se ha seleccionado ningún archivo. Cargue los archivos BAM y BAI.",
  "Extracting...": "Extrayendo...",
  "Processing BAM file extraction...": "Procesando la extracción del archivo BAM...",
  "Submit Jobs": "Enviar trabajos",
  "Your results will appear here after job submission.": "Sus resultados aparecerán aquí tras el envío del trabajo.",
  "Download {name}": "Descargar {name}",
  "Download subset BAM file {name}": "Descargar el archivo BAM reducido {name}",
  "Download subset BAI file {name}": "Descargar el archivo BAI reducido {name}",
  "Invalid Job ID provided": "El ID de trabajo indicado no es válido",
  "Job failed": "El trabajo ha fallado",
  "Load Job from URL": "Cargar trabajo desde la URL",
  "Cohort Creation": "Creación de cohorte",
  "Cohort failed.": "La cohorte ha fallado.",
  "Cohort passphrase is required to run joint analysis.": "Se requiere la frase de contraseña de la cohorte para ejecutar el análisis conjunto.",
  "Cohort Analysis": "Análisis de cohorte",
  "Initiating joint analysis...": "Iniciando el análisis conjunto...",
  "Analysis in progress...": "Análisis en curso...",
  "Cohort analysis failed.": "El análisis de cohorte ha fallado.",
  "Aioli Initialization": "Inicialización de Aioli",
  "BAM Extraction": "Extracción de BAM",
  "File Selection": "Selección de archivos",
  "Invalid files: {files}": "Archivos no válidos: {files}",
  "File Validation": "Validación de archivos",
  "Job Submission": "Envío del trabajo",
  "Job {id} not found": "Trabajo {id} no encontrado",
  "Job Retry": "Reintento del trabajo",
  "Disclaimer": "Descargo",
  "GDPR explicit consent is required to donate data.": "Para donar datos se requiere el consentimiento explícito conforme al RGPD.",
  "Please select a result ZIP archive to donate.": "Seleccione un archivo ZIP de resultados para donar.",
  "Please select a valid .zip result file.": "Seleccione un archivo de resultados .zip válido.",
  "Confirmation method is required for positive findings.": "Para los hallazgos positivos es obligatorio indicar el método de confirmación.",
  "Verifying and uploading donation...": "Verificando y cargando la donación...",
  "Server responded with {status}: {statusText}": "El servidor respondió con {status}: {statusText}",
  "Remove {name}": "Eliminar {name}",
  "No files selected.": "No se ha seleccionado ningún archivo.",
  "Some files were invalid and not added: {files}": "Algunos archivos no eran válidos y no se añadieron: {files}",
  "Processing files...": "Procesando archivos...",
  "Please enter a valid email address (e.g., user@example.com)": "Introduzca una dirección de correo electrónico válida (p. ej., user@example.com)",
  "Valid email address": "Dirección de correo electrónico válida",
  "Cohort alias must be 3-64 characters (letters, numbers, spaces, hyphens, underscores)": "El alias de cohorte debe tener entre 3 y 64 caracteres (letras, números, espacios, guiones, guiones bajos)",
  "Valid cohort alias": "Alias de cohorte válido",
  "Passphrase must be 8-128 characters long": "La frase de contraseña debe tener entre 8 y 128 caracteres",
  "Valid passphrase": "Frase de contraseña válida",
  "Job ID: ": "ID de trabajo: ",
  "Status: ": "Estado: ",
  "Loading cohort details for Cohort ID: ": "Cargando los detalles de la cohorte con ID: ",
  "Loading...": "Cargando...",
  "Loading job details for Job ID: ": "Cargando los detalles del trabajo con ID: ",
  "No logs to download": "No hay registros para descargar",
  "Clear all logs?": "¿Borrar todos los registros?",
  "Cohort ID must be a non-empty string": "El ID de cohorte debe ser una cadena no vacía",
  "Invalid cohort ID format: {id}": "Formato de ID de cohorte no válido: {id}",
  "Job ID must be a non-empty string": "El ID de trabajo debe ser una cadena no vacía",
  "Invalid job ID format: {id}": "Formato de ID de trabajo no válido: {id}",
  "Invalid job status: {status}": "Estado del trabajo no válido: {status}",
  "Polling duration exceeded": "Se ha superado el tiempo máximo de consulta",
  "hg19 (UCSC chr prefix)": "hg19 (UCSC, prefijo chr)",
  "hg38 (UCSC chr prefix)": "hg38 (UCSC, prefijo chr)",
  "GRCh37 (ENSEMBL numeric)": "GRCh37 (ENSEMBL, numérico)",
  "GRCh38 (ENSEMBL numeric)": "GRCh38 (ENSEMBL, numérico)",
  "hg19 (NCBI RefSeq)": "hg19 (NCBI RefSeq)",
  "hg38 (NCBI RefSeq)": "hg38 (NCBI RefSeq)",
  "Request timeout after {timeout}ms": "Tiempo de espera de la solicitud agotado tras {timeout} ms",
  "Request failed with status {status}": "La solicitud ha fallado con el estado {status}",
  "Next": "Siguiente",
  "Back": "Atrás",
  "Done": "Listo",
  "Shareable Link: ": "Enlace para compartir: ",
  "Shareable link for {type} ID {id}": "Enlace para compartir de {type} con ID {id}",
  "Copy link": "Copiar enlace",
  "Failed to copy the link. Please try manually.": "No se pudo copiar el enlace. Cópielo manualmente.",
  "Download vntyper results": "Descargar resultados de vntyper",
  "Download results for Job ID {jobId}": "Descargar los resultados del trabajo con ID {jobId}",
  "Copy Link": "Copiar enlace",
  "Copy shareable link for Job ID {jobId}": "Copiar el enlace para compartir del trabajo con ID {jobId}",
  "Shareable link copied to clipboard!": "¡Enlace para compartir copiado al portapapeles!",
  "Detected reference assembly:": "Ensamblaje de referencia detectado:",
  "Coordinates configured automatically. Please confirm or select manually.": "Coordenadas configuradas automáticamente. Confírmelas o selecciónelas manualmente.",
  "Hide options": "Ocultar opciones",
  "Show options": "Mostrar opciones",
  "Next poll in: {seconds} seconds": "Próxima consulta en: {seconds} segundos",
  "Failed to fetch usage statistics: {status}": "No se pudieron obtener las estadísticas de uso: {status}",
  "Active Jobs": "Trabajos activos",
  "Unique Users": "Usuarios únicos",
  "Active Window Statuses": "Estados en la ventana activa",
  "No active jobs in window": "Sin trabajos activos en la ventana",
  "Cumulative Usage Tracking": "Seguimiento de uso acumulado",
  "All-time jobs: {jobs} | All-time users: {users}": "Trabajos totales: {jobs} | Usuarios totales: {users}",
  "Cumulative tracking recorded since {date}": "Seguimiento acumulado registrado desde {date}",
  "N/A": "N/D",
  "Running Joint Analysis...": "Ejecutando análisis conjunto...",
  "Retry Joint Analysis": "Reintentar análisis conjunto",
  "Analysis Completed": "Análisis completado",
  "Analysis Complete": "Análisis completado",
  "Download Cohort Results (.zip)": "Descargar resultados de la cohorte (.zip)",
  "Cohort: {name}": "Cohorte: {name}",
  "ID: ": "ID: ",
  "Jobs: ": "Trabajos: ",
  "Joint Cohort Analysis": "Análisis conjunto de cohorte",
  "All cohort samples have completed processing. Run joint analysis to aggregate screening calls, compute cohort allele frequencies, and generate summary visualizations.": "Se ha completado el procesamiento de todas las muestras de la cohorte. Ejecute el análisis conjunto para agregar las llamadas de cribado, calcular las frecuencias alélicas de la cohorte y generar visualizaciones de resumen.",
  "Run Joint Analysis": "Ejecutar análisis conjunto",
  "Pending": "Pendiente",
  "Processing": "En proceso",
  "Completed": "Completado",
  "Failed": "Fallido",
  "Validation Error: {message}": "Error de validación: {message}",
  "Network Error": "Error de red",
  "API Error ({statusCode})": "Error de la API ({statusCode})",
  "API Error": "Error de la API",
  "Error": "Error",
  "Download Results": "Descargar resultados",
  "File: ": "Archivo: ",
  "Queued": "En cola",
  "Started": "Iniciado",
  "Cancelled": "Cancelado"
};
