window.I18N = {
  "Invalid Cohort ID provided.": "Ongeldige cohort-ID opgegeven.",
  "Passphrase must be a string.": "Wachtwoordzin moet een tekenreeks zijn.",
  "Invalid Job ID provided.": "Ongeldige taak-ID opgegeven.",
  "Alias must be a string.": "Alias moet een tekenreeks zijn.",
  "Job failed.": "Taak mislukt.",
  "Invalid cohort status data.": "Ongeldige cohortstatusgegevens.",
  "Cohort processing failed.": "Cohortverwerking mislukt.",
  "Invalid alias provided.": "Ongeldige alias opgegeven.",
  "Passphrase is required for cohort analysis.": "Voor cohortanalyse is een wachtwoordzin vereist.",
  "Failed to initialize the virtual filesystem (CLI.fs is undefined).": "Het virtuele bestandssysteem kon niet worden geïnitialiseerd (CLI.fs is undefined).",
  "Failed to initialize the processing environment.": "De verwerkingsomgeving kon niet worden geïnitialiseerd.",
  "⚠️  Pipeline Warning: The Dragen pipeline has known issues aligning reads in the MUC1 VNTR region. For best results, consider using the offline VNtyper CLI in normal mode.": "⚠️  Pipelinewaarschuwing: de Dragen-pipeline heeft bekende problemen met het alignen van reads in de MUC1-VNTR-regio. Overweeg voor de beste resultaten de offline VNtyper-CLI in normale modus te gebruiken.",
  "⚠️  Pipeline Warning: The CLC pipeline has not been fully tested and may have issues aligning reads in the MUC1 VNTR region. Please verify results carefully or use the offline VNtyper CLI.": "⚠️  Pipelinewaarschuwing: de CLC-pipeline is niet volledig getest en kan problemen hebben met het alignen van reads in de MUC1-VNTR-regio. Controleer de resultaten zorgvuldig of gebruik de offline VNtyper-CLI.",
  "No region selected.": "Geen regio geselecteerd.",
  "Processing...": "Verwerken...",
  "Failed to mount SAM file: {name}": "SAM-bestand kon niet worden gekoppeld: {name}",
  "Failed to create Blob from BAM file {file}.": "Blob kon niet worden aangemaakt uit BAM-bestand {file}.",
  "Failed to create Blob from BAI file {file}.": "Blob kon niet worden aangemaakt uit BAI-bestand {file}.",
  "Error: {message}": "Fout: {message}",
  "Extract Region": "Regio extraheren",
  "Submit Job": "Taak indienen",
  "Submitting...": "Indienen...",
  "No files selected. Please upload BAM and BAI files.": "Geen bestanden geselecteerd. Upload BAM- en BAI-bestanden.",
  "Extracting...": "Extraheren...",
  "Processing BAM file extraction...": "BAM-bestand wordt geëxtraheerd...",
  "Submit Jobs": "Taken indienen",
  "Your results will appear here after job submission.": "Uw resultaten verschijnen hier nadat u een taak hebt ingediend.",
  "Download {name}": "{name} downloaden",
  "Download subset BAM file {name}": "Subset-BAM-bestand {name} downloaden",
  "Download subset BAI file {name}": "Subset-BAI-bestand {name} downloaden",
  "Invalid Job ID provided": "Ongeldige taak-ID opgegeven",
  "Job failed": "Taak mislukt",
  "Load Job from URL": "Taak laden via URL",
  "Cohort Creation": "Cohort aanmaken",
  "Cohort failed.": "Cohort mislukt.",
  "Cohort passphrase is required to run joint analysis.": "Voor de gezamenlijke analyse is de wachtwoordzin van het cohort vereist.",
  "Cohort Analysis": "Cohortanalyse",
  "Initiating joint analysis...": "Gezamenlijke analyse wordt gestart...",
  "Analysis in progress...": "Analyse bezig...",
  "Cohort analysis failed.": "Cohortanalyse mislukt.",
  "Aioli Initialization": "Aioli-initialisatie",
  "BAM Extraction": "BAM-extractie",
  "File Selection": "Bestandsselectie",
  "Invalid files: {files}": "Ongeldige bestanden: {files}",
  "File Validation": "Bestandsvalidatie",
  "Job Submission": "Taak indienen",
  "Job {id} not found": "Taak {id} niet gevonden",
  "Job Retry": "Taak opnieuw proberen",
  "Disclaimer": "Disclaimer",
  "GDPR explicit consent is required to donate data.": "Uitdrukkelijke AVG-toestemming is vereist om gegevens te doneren.",
  "Please select a result ZIP archive to donate.": "Selecteer een ZIP-archief met resultaten om te doneren.",
  "Please select a valid .zip result file.": "Selecteer een geldig .zip-resultaatbestand.",
  "Confirmation method is required for positive findings.": "Bij positieve bevindingen is een bevestigingsmethode vereist.",
  "Verifying and uploading donation...": "Donatie wordt gecontroleerd en geüpload...",
  "Server responded with {status}: {statusText}": "Server antwoordde met {status}: {statusText}",
  "Remove {name}": "{name} verwijderen",
  "No files selected.": "Geen bestanden geselecteerd.",
  "Some files were invalid and not added: {files}": "Enkele bestanden waren ongeldig en zijn niet toegevoegd: {files}",
  "Processing files...": "Bestanden verwerken...",
  "Please enter a valid email address (e.g., user@example.com)": "Voer een geldig e-mailadres in (bijv. user@example.com)",
  "Valid email address": "Geldig e-mailadres",
  "Cohort alias must be 3-64 characters (letters, numbers, spaces, hyphens, underscores)": "Cohortalias moet 3-64 tekens bevatten (letters, cijfers, spaties, koppeltekens, underscores)",
  "Valid cohort alias": "Geldige cohortalias",
  "Passphrase must be 8-128 characters long": "Wachtwoordzin moet 8-128 tekens lang zijn",
  "Valid passphrase": "Geldige wachtwoordzin",
  "Job ID: ": "Taak-ID: ",
  "Status: ": "Status: ",
  "Loading cohort details for Cohort ID: ": "Cohortgegevens laden voor cohort-ID: ",
  "Loading...": "Laden...",
  "Loading job details for Job ID: ": "Taakgegevens laden voor taak-ID: ",
  "No logs to download": "Geen logs om te downloaden",
  "Clear all logs?": "Alle logs wissen?",
  "Cohort ID must be a non-empty string": "Cohort-ID mag geen lege tekenreeks zijn",
  "Invalid cohort ID format: {id}": "Ongeldige indeling van cohort-ID: {id}",
  "Job ID must be a non-empty string": "Taak-ID mag geen lege tekenreeks zijn",
  "Invalid job ID format: {id}": "Ongeldige indeling van taak-ID: {id}",
  "Invalid job status: {status}": "Ongeldige taakstatus: {status}",
  "Polling duration exceeded": "Maximale pollingduur overschreden",
  "hg19 (UCSC chr prefix)": "hg19 (UCSC, chr-prefix)",
  "hg38 (UCSC chr prefix)": "hg38 (UCSC, chr-prefix)",
  "GRCh37 (ENSEMBL numeric)": "GRCh37 (ENSEMBL, numeriek)",
  "GRCh38 (ENSEMBL numeric)": "GRCh38 (ENSEMBL, numeriek)",
  "hg19 (NCBI RefSeq)": "hg19 (NCBI RefSeq)",
  "hg38 (NCBI RefSeq)": "hg38 (NCBI RefSeq)",
  "Request timeout after {timeout}ms": "Time-out van verzoek na {timeout}ms",
  "Request failed with status {status}": "Verzoek mislukt met status {status}",
  "Next": "Volgende",
  "Back": "Terug",
  "Done": "Klaar",
  "Shareable Link: ": "Deelbare link: ",
  "Shareable link for {type} ID {id}": "Deelbare link voor {type}-ID {id}",
  "Copy link": "Link kopiëren",
  "Failed to copy the link. Please try manually.": "De link kon niet worden gekopieerd. Kopieer deze handmatig.",
  "Download vntyper results": "vntyper-resultaten downloaden",
  "Download results for Job ID {jobId}": "Resultaten voor taak-ID {jobId} downloaden",
  "Copy Link": "Link kopiëren",
  "Copy shareable link for Job ID {jobId}": "Deelbare link voor taak-ID {jobId} kopiëren",
  "Shareable link copied to clipboard!": "Deelbare link naar klembord gekopieerd!",
  "Detected reference assembly:": "Gedetecteerde referentie-assembly:",
  "Coordinates configured automatically. Please confirm or select manually.": "Coördinaten automatisch ingesteld. Bevestig of selecteer handmatig.",
  "Hide options": "Opties verbergen",
  "Show options": "Opties tonen",
  "Next poll in: {seconds} seconds": "Volgende poll over: {seconds} seconden",
  "Failed to fetch usage statistics: {status}": "Gebruiksstatistieken konden niet worden opgehaald: {status}",
  "Active Jobs": "Actieve taken",
  "Unique Users": "Unieke gebruikers",
  "Active Window Statuses": "Statussen in actief venster",
  "No active jobs in window": "Geen actieve taken in venster",
  "Cumulative Usage Tracking": "Cumulatief gebruik",
  "All-time jobs: {jobs} | All-time users: {users}": "Taken totaal: {jobs} | Gebruikers totaal: {users}",
  "Cumulative tracking recorded since {date}": "Cumulatieve registratie sinds {date}",
  "N/A": "n.v.t.",
  "Running Joint Analysis...": "Gezamenlijke analyse bezig...",
  "Retry Joint Analysis": "Gezamenlijke analyse opnieuw proberen",
  "Analysis Completed": "Analyse voltooid",
  "Analysis Complete": "Analyse voltooid",
  "Download Cohort Results (.zip)": "Cohortresultaten downloaden (.zip)",
  "Cohort: {name}": "Cohort: {name}",
  "ID: ": "ID: ",
  "Jobs: ": "Taken: ",
  "Joint Cohort Analysis": "Gezamenlijke cohortanalyse",
  "All cohort samples have completed processing. Run joint analysis to aggregate screening calls, compute cohort allele frequencies, and generate summary visualizations.": "Alle samples van het cohort zijn verwerkt. Voer de gezamenlijke analyse uit om screeningcalls samen te voegen, allelfrequenties binnen het cohort te berekenen en samenvattende visualisaties te genereren.",
  "Run Joint Analysis": "Gezamenlijke analyse uitvoeren",
  "Pending": "In afwachting",
  "Processing": "Bezig",
  "Completed": "Voltooid",
  "Failed": "Mislukt",
  "Validation Error: {message}": "Validatiefout: {message}",
  "Network Error": "Netwerkfout",
  "API Error ({statusCode})": "API-fout ({statusCode})",
  "API Error": "API-fout",
  "Error": "Fout",
  "Download Results": "Resultaten downloaden",
  "File: ": "Bestand: ",
  "Queued": "In wachtrij",
  "Started": "Gestart",
  "Cancelled": "Geannuleerd"
};
