window.I18N = {
  "Invalid Cohort ID provided.": "Identifiant de cohorte invalide.",
  "Passphrase must be a string.": "La phrase secrète doit être une chaîne de caractères.",
  "Invalid Job ID provided.": "Identifiant de tâche invalide.",
  "Alias must be a string.": "L'alias doit être une chaîne de caractères.",
  "Job failed.": "La tâche a échoué.",
  "Invalid cohort status data.": "Données de statut de cohorte invalides.",
  "Cohort processing failed.": "Le traitement de la cohorte a échoué.",
  "Invalid alias provided.": "Alias invalide.",
  "Passphrase is required for cohort analysis.": "Une phrase secrète est requise pour l'analyse de cohorte.",
  "Failed to initialize the virtual filesystem (CLI.fs is undefined).": "Échec de l'initialisation du système de fichiers virtuel (CLI.fs n'est pas défini).",
  "Failed to initialize the processing environment.": "Échec de l'initialisation de l'environnement de traitement.",
  "⚠️  Pipeline Warning: The Dragen pipeline has known issues aligning reads in the MUC1 VNTR region. For best results, consider using the offline VNtyper CLI in normal mode.": "⚠️  Avertissement pipeline : le pipeline Dragen présente des problèmes connus d'alignement des lectures dans la région du VNTR de MUC1. Pour de meilleurs résultats, envisagez d'utiliser l'outil hors ligne VNtyper CLI en mode normal.",
  "⚠️  Pipeline Warning: The CLC pipeline has not been fully tested and may have issues aligning reads in the MUC1 VNTR region. Please verify results carefully or use the offline VNtyper CLI.": "⚠️  Avertissement pipeline : le pipeline CLC n'a pas été entièrement testé et peut présenter des problèmes d'alignement des lectures dans la région du VNTR de MUC1. Veuillez vérifier soigneusement les résultats ou utiliser l'outil hors ligne VNtyper CLI.",
  "No region selected.": "Aucune région sélectionnée.",
  "Processing...": "Traitement...",
  "Failed to mount SAM file: {name}": "Échec du montage du fichier SAM : {name}",
  "Failed to create Blob from BAM file {file}.": "Échec de la création du Blob à partir du fichier BAM {file}.",
  "Failed to create Blob from BAI file {file}.": "Échec de la création du Blob à partir du fichier BAI {file}.",
  "Error: {message}": "Erreur : {message}",
  "Extract Region": "Extraire la région",
  "Submit Job": "Soumettre la tâche",
  "Submitting...": "Soumission...",
  "No files selected. Please upload BAM and BAI files.": "Aucun fichier sélectionné. Veuillez téléverser des fichiers BAM et BAI.",
  "Extracting...": "Extraction...",
  "Processing BAM file extraction...": "Extraction du fichier BAM en cours...",
  "Submit Jobs": "Soumettre les tâches",
  "Your results will appear here after job submission.": "Vos résultats s'afficheront ici après la soumission des tâches.",
  "Download {name}": "Télécharger {name}",
  "Download subset BAM file {name}": "Télécharger le fichier BAM extrait {name}",
  "Download subset BAI file {name}": "Télécharger le fichier BAI extrait {name}",
  "Invalid Job ID provided": "Identifiant de tâche invalide",
  "Job failed": "Échec de la tâche",
  "Load Job from URL": "Charger la tâche depuis l'URL",
  "Cohort Creation": "Création de la cohorte",
  "Cohort failed.": "Échec de la cohorte.",
  "Cohort passphrase is required to run joint analysis.": "Une phrase secrète de cohorte est requise pour lancer l'analyse conjointe.",
  "Cohort Analysis": "Analyse de cohorte",
  "Initiating joint analysis...": "Lancement de l'analyse conjointe...",
  "Analysis in progress...": "Analyse en cours...",
  "Cohort analysis failed.": "L'analyse de cohorte a échoué.",
  "Aioli Initialization": "Initialisation d'Aioli",
  "BAM Extraction": "Extraction BAM",
  "File Selection": "Sélection des fichiers",
  "Invalid files: {files}": "Fichiers invalides : {files}",
  "File Validation": "Validation des fichiers",
  "Job Submission": "Soumission de la tâche",
  "Job {id} not found": "Tâche {id} introuvable",
  "Job Retry": "Relance de la tâche",
  "Disclaimer": "Avis",
  "GDPR explicit consent is required to donate data.": "Le consentement explicite au titre du RGPD est requis pour faire don de données.",
  "Please select a result ZIP archive to donate.": "Veuillez sélectionner une archive ZIP de résultats à donner.",
  "Please select a valid .zip result file.": "Veuillez sélectionner un fichier de résultats .zip valide.",
  "Confirmation method is required for positive findings.": "La méthode de confirmation est requise pour les résultats positifs.",
  "Verifying and uploading donation...": "Vérification et téléversement du don...",
  "Server responded with {status}: {statusText}": "Le serveur a répondu {status} : {statusText}",
  "Remove {name}": "Retirer {name}",
  "No files selected.": "Aucun fichier sélectionné.",
  "Some files were invalid and not added: {files}": "Certains fichiers étaient invalides et n'ont pas été ajoutés : {files}",
  "Processing files...": "Traitement des fichiers...",
  "Please enter a valid email address (e.g., user@example.com)": "Veuillez saisir une adresse e-mail valide (p. ex. user@example.com)",
  "Valid email address": "Adresse e-mail valide",
  "Cohort alias must be 3-64 characters (letters, numbers, spaces, hyphens, underscores)": "L'alias de cohorte doit comporter de 3 à 64 caractères (lettres, chiffres, espaces, traits d'union, tirets bas)",
  "Valid cohort alias": "Alias de cohorte valide",
  "Passphrase must be 8-128 characters long": "La phrase secrète doit comporter de 8 à 128 caractères",
  "Valid passphrase": "Phrase secrète valide",
  "Job ID: ": "Identifiant de tâche : ",
  "Status: ": "Statut : ",
  "Loading cohort details for Cohort ID: ": "Chargement des détails de la cohorte pour l'identifiant : ",
  "Loading...": "Chargement...",
  "Loading job details for Job ID: ": "Chargement des détails de la tâche pour l'identifiant : ",
  "No logs to download": "Aucun journal à télécharger",
  "Clear all logs?": "Effacer tous les journaux ?",
  "Cohort ID must be a non-empty string": "L'identifiant de cohorte doit être une chaîne non vide",
  "Invalid cohort ID format: {id}": "Format d'identifiant de cohorte invalide : {id}",
  "Job ID must be a non-empty string": "L'identifiant de tâche doit être une chaîne non vide",
  "Invalid job ID format: {id}": "Format d'identifiant de tâche invalide : {id}",
  "Invalid job status: {status}": "Statut de tâche invalide : {status}",
  "Polling duration exceeded": "Durée d'interrogation dépassée",
  "hg19 (UCSC chr prefix)": "hg19 (préfixe chr UCSC)",
  "hg38 (UCSC chr prefix)": "hg38 (préfixe chr UCSC)",
  "GRCh37 (ENSEMBL numeric)": "GRCh37 (ENSEMBL, numérique)",
  "GRCh38 (ENSEMBL numeric)": "GRCh38 (ENSEMBL, numérique)",
  "hg19 (NCBI RefSeq)": "hg19 (NCBI RefSeq)",
  "hg38 (NCBI RefSeq)": "hg38 (NCBI RefSeq)",
  "Request timeout after {timeout}ms": "Délai de la requête dépassé après {timeout}ms",
  "Request failed with status {status}": "Échec de la requête avec le statut {status}",
  "Next": "Suivant",
  "Back": "Précédent",
  "Done": "Terminer",
  "Shareable Link: ": "Lien de partage : ",
  "Shareable link for {type} ID {id}": "Lien de partage ({type}, ID {id})",
  "Copy link": "Copier le lien",
  "Failed to copy the link. Please try manually.": "Échec de la copie du lien. Veuillez le copier manuellement.",
  "Download vntyper results": "Télécharger les résultats vntyper",
  "Download results for Job ID {jobId}": "Télécharger les résultats de la tâche {jobId}",
  "Copy Link": "Copier le lien",
  "Copy shareable link for Job ID {jobId}": "Copier le lien de partage de la tâche {jobId}",
  "Shareable link copied to clipboard!": "Lien de partage copié dans le presse-papiers !",
  "Detected reference assembly:": "Assemblage de référence détecté :",
  "Coordinates configured automatically. Please confirm or select manually.": "Coordonnées configurées automatiquement. Veuillez confirmer ou sélectionner manuellement.",
  "Hide options": "Masquer les options",
  "Show options": "Afficher les options",
  "Next poll in: {seconds} seconds": "Prochaine interrogation dans : {seconds} secondes",
  "Failed to fetch usage statistics: {status}": "Échec de la récupération des statistiques d'utilisation : {status}",
  "Active Jobs": "Tâches actives",
  "Unique Users": "Utilisateurs uniques",
  "Active Window Statuses": "Statuts de la fenêtre active",
  "No active jobs in window": "Aucune tâche active dans la fenêtre",
  "Cumulative Usage Tracking": "Suivi cumulé de l'utilisation",
  "All-time jobs: {jobs} | All-time users: {users}": "Tâches au total : {jobs} | Utilisateurs au total : {users}",
  "Cumulative tracking recorded since {date}": "Suivi cumulé enregistré depuis le {date}",
  "N/A": "N/D",
  "Running Joint Analysis...": "Analyse conjointe en cours...",
  "Retry Joint Analysis": "Relancer l'analyse conjointe",
  "Analysis Completed": "Analyse terminée",
  "Analysis Complete": "Analyse terminée",
  "Download Cohort Results (.zip)": "Télécharger les résultats de la cohorte (.zip)",
  "Cohort: {name}": "Cohorte : {name}",
  "ID: ": "ID : ",
  "Jobs: ": "Tâches : ",
  "Joint Cohort Analysis": "Analyse conjointe de cohorte",
  "All cohort samples have completed processing. Run joint analysis to aggregate screening calls, compute cohort allele frequencies, and generate summary visualizations.": "Le traitement de tous les échantillons de la cohorte est terminé. Lancez l'analyse conjointe pour agréger les appels de dépistage, calculer les fréquences alléliques de la cohorte et générer des visualisations de synthèse.",
  "Run Joint Analysis": "Lancer l'analyse conjointe",
  "Pending": "En attente",
  "Processing": "En cours",
  "Completed": "Terminé",
  "Failed": "Échec",
  "Validation Error: {message}": "Erreur de validation : {message}",
  "Network Error": "Erreur réseau",
  "API Error ({statusCode})": "Erreur d'API ({statusCode})",
  "API Error": "Erreur d'API",
  "Error": "Erreur",
  "Download Results": "Télécharger les résultats",
  "File: ": "Fichier : ",
  "Queued": "En file d'attente",
  "Started": "Démarré",
  "Cancelled": "Annulé"
};
